-- MySQL Script generated by MySQL Workbench
-- Sun Oct 24 17:03:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema article_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema article_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `article_service` DEFAULT CHARACTER SET utf8 ;
USE `article_service` ;

-- -----------------------------------------------------
-- Table `article_service`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_service`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `isModerator` TINYINT NOT NULL,
  `isActive` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_service`.`articleVersion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_service`.`articleVersion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `editorUserId` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `originalId` INT NULL,
  `articleId` INT NULL,
  `name` VARCHAR(255) NOT NULL,
  `text` TEXT(2000) NOT NULL,
  `status` ENUM('new', 'accepted', 'declined') NOT NULL,
  `moderatorUserId` INT NULL,
  `moderatedDate` DATETIME NULL,
  `declineReason` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articleVersion_article_idx` (`articleId` ASC) VISIBLE,
  INDEX `fk_articleVersion_user_editorUserId_idx` (`editorUserId` ASC) VISIBLE,
  INDEX `fk_articleVersion_user_moderatorUserId_idx` (`moderatorUserId` ASC) VISIBLE,
  INDEX `fk_articleVersion_articleVersion_idx` (`originalId` ASC) INVISIBLE,
  INDEX `articleVersion_date_idx` (`date` ASC) INVISIBLE,
  INDEX `articleVersion_moderatedDate_idx` (`moderatedDate` ASC) VISIBLE,
  CONSTRAINT `fk_articleVersion_article`
    FOREIGN KEY (`articleId`)
    REFERENCES `article_service`.`article` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_articleVersion_user_editorUserId`
    FOREIGN KEY (`editorUserId`)
    REFERENCES `article_service`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_articleVersion_user_moderatorUserId`
    FOREIGN KEY (`moderatorUserId`)
    REFERENCES `article_service`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_articleVersion_articleVersion`
    FOREIGN KEY (`originalId`)
    REFERENCES `article_service`.`articleVersion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_service`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_service`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `authorUserId` INT NOT NULL,
  `text` TEXT(2000) NOT NULL,
  `versionId` INT NOT NULL,
  `publishDate` DATETIME NOT NULL,
  `lastModificationDate` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_user_idx` (`authorUserId` ASC) VISIBLE,
  INDEX `articleVersion_date_idx_idx` (`versionId` ASC) VISIBLE,
  CONSTRAINT `fk_article_user`
    FOREIGN KEY (`authorUserId`)
    REFERENCES `article_service`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_articleVersion`
    FOREIGN KEY (`versionId`)
    REFERENCES `article_service`.`articleVersion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_service`.`userLogins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_service`.`userLogins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `token` VARCHAR(50) NOT NULL,
  `loginDate` DATETIME NOT NULL,
  `logoutDate` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  INDEX `fk_userLogins_user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_userLogins_user`
    FOREIGN KEY (`userId`)
    REFERENCES `article_service`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;