"""Create other tables

Revision ID: aab0f969fa26
Revises: f1d659875c15
Create Date: 2021-10-25 10:14:05.696883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab0f969fa26'
down_revision = 'f1d659875c15'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('authorUserId', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('versionId', sa.Integer(), nullable=False),
    sa.Column('publishDate', sa.DateTime(), nullable=False),
    sa.Column('lastModificationDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authorUserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_authorUserId'), 'article', ['authorUserId'], unique=False)
    op.create_index(op.f('ix_article_versionId'), 'article', ['versionId'], unique=False)
    op.create_table('articleversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editorUserId', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('originalId', sa.Integer(), nullable=True),
    sa.Column('articleId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'accepted', 'declined'), nullable=False),
    sa.Column('moderatorUserId', sa.Integer(), nullable=True),
    sa.Column('moderatedDate', sa.DateTime(), nullable=True),
    sa.Column('declineReason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['articleId'], ['article.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['editorUserId'], ['user.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['moderatorUserId'], ['user.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['originalId'], ['articleversion.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articleversion_articleId'), 'articleversion', ['articleId'], unique=False)
    op.create_index(op.f('ix_articleversion_editorUserId'), 'articleversion', ['editorUserId'], unique=False)
    op.create_index(op.f('ix_articleversion_moderatedDate'), 'articleversion', ['moderatedDate'], unique=False)
    op.create_index(op.f('ix_articleversion_moderatorUserId'), 'articleversion', ['moderatorUserId'], unique=False)
    op.create_table('userlogins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('loginDate', sa.DateTime(), nullable=False),
    sa.Column('logoutDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_userlogins_userId'), 'userlogins', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userlogins_userId'), table_name='userlogins')
    op.drop_table('userlogins')
    op.drop_index(op.f('ix_articleversion_moderatorUserId'), table_name='articleversion')
    op.drop_index(op.f('ix_articleversion_moderatedDate'), table_name='articleversion')
    op.drop_index(op.f('ix_articleversion_editorUserId'), table_name='articleversion')
    op.drop_index(op.f('ix_articleversion_articleId'), table_name='articleversion')
    op.drop_table('articleversion')
    op.drop_index(op.f('ix_article_versionId'), table_name='article')
    op.drop_index(op.f('ix_article_authorUserId'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
