"""alembic

Revision ID: ede81fd5506f
Revises: b1649d835ab7
Create Date: 2021-11-10 14:51:09.551817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede81fd5506f'
down_revision = 'b1649d835ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
